apiVersion: v1
kind: Service
metadata:
  name: ts43-eke-aaa-cookie-verify
  namespace: kong
spec:
  selector:
    app: ts43-eke-aaa-cookie-verify
  ports:
    - name: TCP
      port: 80
      targetPort: 8080
