apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: kong-plugin-myheader
    namespace: kong
    files:
      - custom-log-plugin/handler.lua
      - custom-log-plugin/schema.lua
generatorOptions:
  disableNameSuffixHash: true