apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: custom-hello
    namespace: kong
    files:
      - custom-hello/handler.lua
      - custom-hello/schema.lua
generatorOptions:
  disableNameSuffixHash: true