apiVersion: v1
kind: Service
metadata:
  name: ts43-eke-aaa-cookie
  namespace: kong
spec:
  selector:
    app: ts43-eke-aaa-cookie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
