apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-otel
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: opentelemetry
config:
  logs_endpoint: http://otel-collector.monitoring.svc.cluster.local:4318/v1/logs