apiVersion: v1
kind: Namespace
metadata:
  name: aggregates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: aggregates
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: aggregates
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon        Off
        Flush         1
        Parsers_File  parsers.conf
        Log_Level     info
        storage.path  /buffers
        storage.sync  normal
        storage.metrics on
        storage.total_limit_size 10G

    [INPUT]
        Name                  tail
        Path                  /var/log/containers/*.log
        Tag                   kube.*
        Parser                cri
        DB                    /buffers/tail.db
        DB.Sync               Normal
        storage.type          filesystem
        Mem_Buf_Limit         50MB
        Refresh_Interval      5
        Skip_Long_Lines       On
        Read_from_Head        Off
        Path_Key              path
        Exclude_Path          /var/log/containers/fluent-bit*_aggregates_fluent-bit-*.log

    # STAGE 1: Select ONLY the log lines from your custom plugin
    #[FILTER]
    # Name   grep
    #Match  kube.*
    #Regex  log  \[custom-log-plugin\]


    [FILTER]
        Name   rewrite_tag
        Match  kube.*
        Rule   log  \[custom-log-plugin\]  custom.plugin true

    # STAGE 2: Parse the logs that passed the grep filter
    [FILTER]
        Name      parser
        Match     kube.*
        Key_Name  log
        Parser    json_in_text
        Reserve_Data On

    # STAGE 3: Run your Lua script on the successfully parsed logs
    [FILTER]
        Name   lua
        Match  kube.*
        script bucket.lua
        call   add_bucket

    [FILTER]
        Name    grep
        Match   kube.*
        Exclude path  .*\/fluent-bit.*_aggregates_fluent-bit-.*\.log$

    [FILTER]
        Name modify
        Match kube.*
        Rename timestamp @timestamp

    [FILTER]
        Name      parser
        Match     custom.plugin
        Key_Name  log
        Parser    json_in_text
        Reserve_Data On
        Preserve_Key On

    [OUTPUT]
        Name    http
        Match   kube.*
        Host    log-sink-svc
        Port    8080
        URI     /ingest
        Format  json
        Json_date_key timestamp
        Retry_Limit False

    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch-master.monitoring.svc.cluster.local
        Port  9200
        HTTP_User elastic
        HTTP_Passwd QGkMi6Iy0LxQQSS0
        TLS   On
        TLS.Verify Off
        Index fluentbit-%Y.%m.%d
        Logstash_Format On
        Logstash_Prefix fluentbit
        Suppress_Type_Name On


  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        json_in_text
        Format      regex
        Regex       ^(?<__prefix>.*?)(?<json>\{.*\})(?<__suffix>.*)$
        Decode_Field_As json json

  bucket.lua: |
    function add_bucket(tag, ts, rec)
      local r = rec["json"] or rec
      local iso = r["timestamp"]
      if not iso then return 1, ts, rec end
      local y,M,d,H = string.match(iso, "^(%d+)%-(%d+)%-(%d+)T(%d+)")
      if y and M and d and H then
        r["datatime"] = string.format("%s-%s-%s %s:00:00", y,M,d,H)
        if rec["json"] then rec["json"] = r else rec = r end
      end
      return 1, ts, rec
    end
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: aggregates
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      securityContext:
        seLinuxOptions:
          type: spc_t
      serviceAccountName: fluent-bit
      tolerations:
        - operator: Exists
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: buffers
              mountPath: /buffers
            - name: config
              mountPath: /fluent-bit/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: buffers
          hostPath:
            path: /var/lib/fluent-bit-buffers
        - name: config
          configMap:
            name: fluent-bit-config
