#!/bin/bash

# ==============================================================================
#  Kong Analytics - New Client Onboarding Script (Interactive)
# ==============================================================================
#
#  This script interactively prompts for the necessary information to create
#  a dedicated BigQuery dataset and a scoped Service Account for a new client.
#
#  Usage:
#  ./onboard_client.sh
#  (No arguments needed)
#
# ==============================================================================

# --- 1. Get GCP Project ID Interactively ---
# Attempt to get the current project from gcloud config as a default
CURRENT_PROJECT_ID=$(gcloud config get-value project 2>/dev/null)

echo "Please enter the GCP Project ID."
read -p "Project ID [default: ${CURRENT_PROJECT_ID}]: " GCP_PROJECT_ID
# If the user just presses enter, use the detected default
GCP_PROJECT_ID=${GCP_PROJECT_ID:-$CURRENT_PROJECT_ID}

if [ -z "$GCP_PROJECT_ID" ]; then
    echo "error: GCP Project ID cannot be empty."
    exit 1
fi

# --- 2. Get Client Name Interactively ---
echo ""
echo "Please enter a name for the new client."
echo "Use a short, lowercase, URL-friendly name (e.g., 'shush-demandpartner', 'shush-entriprise')."
read -p "Client Name: " CLIENT_NAME_INPUT

if [ -z "$CLIENT_NAME_INPUT" ]; then
    echo "error: Client Name cannot be empty."
    exit 1
fi

# --- 3. Define and Confirm Resource Names ---
# Format client name to be safe for resource naming
CLIENT_NAME=$(echo "$CLIENT_NAME_INPUT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
BQ_DATASET_ID="${CLIENT_NAME}_kong_analytics"
SA_NAME="${CLIENT_NAME}-kong-aggregator"
SA_EMAIL="${SA_NAME}@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

echo "--------------------------------------------------"
echo "The following resources will be created:"
echo "--------------------------------------------------"
echo "Project ID:         $GCP_PROJECT_ID"
echo "BigQuery Dataset:   $BQ_DATASET_ID"
echo "Service Account:    $SA_NAME"
echo "Key File Name:      ./gcp/${CLIENT_NAME}-sa-key.json"
echo "--------------------------------------------------"
read -p "Do you want to proceed? (y/n): " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Operation cancelled."
    exit 1
fi

# --- 4. Configure gcloud CLI ---
gcloud config set project "$GCP_PROJECT_ID"

# --- 5. Create the BigQuery Dataset ---
echo -e "\n[STEP 1/4] Creating BigQuery dataset: $BQ_DATASET_ID..."
if bq mk --dataset --description="Analytics data for client ${CLIENT_NAME}" "${GCP_PROJECT_ID}:${BQ_DATASET_ID}"; then
    echo "Dataset created successfully."
else
    echo "Warning: Dataset might already exist. Continuing..."
fi

# --- 6. Create the Dedicated Service Account ---
echo -e "\n[STEP 2/4] Creating Service Account: $SA_NAME..."
if gcloud iam service-accounts create "$SA_NAME" --display-name="Service Account for ${CLIENT_NAME} Kong Analytics"; then
    echo "Service Account created successfully."
else
    echo "Warning: Service Account might already exist. Continuing..."
fi

# --- 7. Grant Scoped IAM Permissions ---
echo -e "\n[STEP 3/4] Granting IAM permissions..."

echo " -> Granting 'BigQuery Job User' role at the project level..."
gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/bigquery.jobUser" --condition=None > /dev/null

echo " -> Granting 'BigQuery Data Editor' role on dataset '$BQ_DATASET_ID'..."
bq show --format=prettyjson "${GCP_PROJECT_ID}:${BQ_DATASET_ID}" > dataset_policy.json
if command -v jq &> /dev/null; then
    jq ".access += [{\"role\": \"WRITER\", \"userByEmail\": \"${SA_EMAIL}\"}]" dataset_policy.json > updated_policy.json
else
    sed -i '$ d' dataset_policy.json
    echo " ,{\"role\": \"WRITER\", \"userByEmail\": \"${SA_EMAIL}\"}]}" >> dataset_policy.json
    mv dataset_policy.json updated_policy.json
fi
bq update --source updated_policy.json "${GCP_PROJECT_ID}:${BQ_DATASET_ID}"
rm dataset_policy.json updated_policy.json
echo "IAM permissions granted successfully."

# --- 8. Create and Download the Service Account Key ---
echo -e "\n[STEP 4/4] Creating and downloading JSON key..."
gcloud iam service-accounts keys create "./gcp/key.json" \
    --iam-account="${SA_EMAIL}"

# --- 9. Generate Kubernetes Configuration ---
echo -e "\n[STEP 5/5] Generating Kubernetes config file: config-${CLIENT_NAME}.yaml"

# Use a 'here document' to write the YAML file content
cat <<EOF > ./config-${CLIENT_NAME}.yaml
# This file was auto-generated by the onboarding script
apiVersion: v1
kind: ConfigMap
metadata:s
  name: aggregator-config-${CLIENT_NAME}
  namespace: default
data:
  GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
  GCP_SERVICE_ACCOUNT_EMAIL: "${SA_EMAIL}"
  BIGQUERY_DATASET: "${BQ_DATASET_ID}"
  BIGQUERY_TABLE: "kong_aggregate"
  SERVICE_ACCOUNT_FILE_PATH: "/gcp/key.json"
  PRICING_FILE_PATH: "/config/pricing.csv"
EOF


# --- 10. Final Output ---
echo "Successfully generated ./config-${CLIENT_NAME}.yaml"
echo ""
echo "Next steps:"
echo "1. Create the Kubernetes secret: kubectl create secret generic ${CLIENT_NAME}-gcp-sa-key --from-file=key.json=./${CLIENT_NAME}-sa-key.json"
echo "2. Apply the generated config: kubectl apply -f ./config-${CLIENT_NAME}.yaml"
echo "3. Deploy the client's dedicated aggregator instance."
