# apps/kong/on-perm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

# resources:
#   - ../custom-plugins 

# Point to your single, merged patch file
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: kong-kong
      namespace: kong